fix: Update requests to recipe service to accept new structure of rec…
Moody-Foodies/brain-food-be pull request #43
Opened 2024-06-04 22:37 UTC by JackCSweeney

## Type of change
- [ ] New feature
- [x] Bug Fix
- [ ] Test
- [ ] Refactor/Style

## Description
Relevant User Story(s):
This branch adds the following changes:
- Updates Recipe PORO to fit with new structure of data being sent from recipe micro service application
- Tests updated to reflect new structure of data coming from micro service and continue to pass

## Check the correct boxes
- [x] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

## Testing Changes
- [ ] No Tests have been changed
- [x] Some Tests have been changed
- [ ] All of the Tests have been changed

## Checklist:
- [x] My code has no unused/commented out code
- [x] I have reviewed my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have fully tested my code

2024-06-04 23:43 UTC, IgorrMagalhaess requested changes
Just delete the cassettes before pushing and we are good to go!

2024-06-04 23:43 UTC, IgorrMagalhaess commented on spec/fixtures/vcr_cassettes/MoodService/_create_user_mood/creates_user_mood.yml
Could you delete the VCR cassettes and push it again? CI won't pass with the cassettes.

2024-06-05 14:14 UTC, JackCSweeney commented on spec/fixtures/vcr_cassettes/MoodService/_create_user_mood/creates_user_mood.yml
Done! Just pushed again with the vcr cassettes folder removed! Sorry, have not used VCR in quite a while for mocking/stubbing

2024-06-05 15:31 UTC, mfaisalnazari approved these changes

2024-06-05 19:10 UTC, IgorrMagalhaess approved these changes

2024-06-05 19:10 UTC, merged